### ISSUE TITLE
"2Checkout Payments Failed: ‘Unauthorized’"

### ISSUE THREAD

**Issue by tejastank** [2Checkout/2checkout-php#31]
"2Checkout Payments Failed: ‘Unauthorized’"

I confirm its production URL and all API keys are correct 

Card working well with linode or digitalocean, but it keep fail with 2checkout ?

Please guide, we just getting "2Checkout Payments Failed: ‘Unauthorized’"

In browser console, For onsite woocommerce payment I got below info
success {"validationErrors":null,"exception":null,"response""type":"TokenResponse","token""dateCreated":1502304151773,"token":"MjRlZjRjZDMtNzRlNS00MWNjLWFlNTItYzg2MGQ5OWIwNWJj"},"paymentMethod""expMonth":"04","expYear":"2021","cardType":"VS","cardNum":"XXXX-XXXX-XXXX-555"},"errors":null}}

What should I do !!! , urgent guide requiured.

**Comment by craigchristenson** [comment]
2Checkout will need to troubleshoot your integration directly. Please contact them at techsupport@2checkout.com with your 2Checkout account number so that they can troubleshoot. If you cannot get a resolution, feel free to reach out to me directly using the email address on my github profile and I'll be happy to help you.
